# Generated by Antigravity on 2026-03-12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        # --- HushraCredentials Adjustments ---
        migrations.AddField(
            model_name='hushracredentials',
            name='request_count',
            field=models.IntegerField(default=0),
        ),

        # --- Proxy Model ---
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('fail_count', models.IntegerField(default=0)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Proxies',
            },
        ),

        # --- SearchTask Status Update ---
        migrations.AlterField(
            model_name='searchtask',
            name='status',
            field=models.CharField(
                choices=[
                    ('PENDING', 'Pending'),
                    ('IN_PROGRESS', 'In Progress'),
                    ('COMPLETED', 'Completed'),
                    ('FAILED', 'Failed'),
                    ('TOO_BROAD', 'Too Broad'),
                ],
                default='PENDING',
                max_length=20
            ),
        ),

        # --- PersonRecord Improvements ---
        migrations.AlterField(
            model_name='personrecord',
            name='ssn',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='personrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
