# Generated by Antigravity on 2026-03-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_stealth_efficiency_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchtask',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='searchtask',
            name='status',
            field=models.CharField(
                choices=[
                    ('PENDING', 'Pending'),
                    ('IN_PROGRESS', 'In Progress'),
                    ('COMPLETED', 'Completed'),
                    ('FAILED', 'Failed'),
                    ('TOO_BROAD', 'Too Broad'),
                    ('STOPPED', 'Stopped'),
                    ('ABORTED', 'Aborted'),
                ],
                default='PENDING',
                max_length=20,
            ),
        ),
    ]
