# Generated by Django 5.2.12 on 2026-03-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_add_global_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchjob',
            name='status',
            field=models.CharField(choices=[('RUNNING', 'Running'), ('STOPPED', 'Stopped'), ('COMPLETED', 'Completed')], default='RUNNING', max_length=20),
        ),
    ]
