# Generated by Django 5.2.12 on 2026-03-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_searchjob_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsetting',
            name='value',
            field=models.CharField(default='true', max_length=255),
        ),
    ]
