# Generated by Django 5.2.12 on 2026-03-13 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0007_searchtask_axis_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(db_index=True, max_length=2)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('priority', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=10)),
                ('axes_enabled', models.JSONField(default=list)),
                ('max_concurrent_tasks', models.IntegerField(default=100)),
                ('min_queue_depth', models.IntegerField(default=50)),
                ('total_primes', models.IntegerField(default=0)),
                ('primes_completed', models.IntegerField(default=0)),
                ('total_tasks', models.IntegerField(default=0)),
                ('tasks_pending', models.IntegerField(default=0)),
                ('tasks_in_progress', models.IntegerField(default=0)),
                ('tasks_completed', models.IntegerField(default=0)),
                ('tasks_failed', models.IntegerField(default=0)),
                ('total_records', models.IntegerField(default=0)),
                ('avg_task_duration', models.FloatField(default=0.0)),
                ('tasks_per_minute', models.FloatField(default=0.0)),
                ('records_per_task', models.FloatField(default=0.0)),
                ('duplicate_rate', models.FloatField(default=0.0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_completion', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_runs', to='scraper.searchjob')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='searchtask',
            name='state_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='scraper.staterun'),
        ),
        migrations.AddIndex(
            model_name='staterun',
            index=models.Index(fields=['state', 'status'], name='scraper_sta_state_74c8fe_idx'),
        ),
        migrations.AddIndex(
            model_name='staterun',
            index=models.Index(fields=['job', 'state'], name='scraper_sta_job_id_4b9652_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='staterun',
            unique_together={('job', 'state')},
        ),
    ]
